### ISSUE TITLE
Visual Studio 2017 on Windows 10 with Azure CLI 2.0 in Linux Subsystem

### ISSUE THREAD

**Issue by mikermesh** [Azure-Samples/app-service-msi-keyvault-dotnet#3]
I'm running the application on my local developer VM which is Windows 10 with Visual Studio 2017. The VM has the Linux Subsystem enabled with Azure CLI 2.0 installed. We currently don't have an on-prem Active Directory environment so the machine is not domain-joined. 

I am logged in to my subscription via Azure CLI 2.0 but when I debug a new instance from Visual Studio I get an error which include the following.

Exception Message: Tried to get token using Azure CLI. Access token could not be acquired. 'az' is not recognized as an internal or external command, operable program or batch file.

**Comment by varunsh-msft** [comment]
Please see the Azure CLI section here. You may need to set the AzureCLIPath environment variable to where Azure CLI is installed. Please let me know if this does not work. 
https://docs.microsoft.com/en-us/azure/key-vault/service-to-service-authentication

There is also an option to use Visual Studio account (using a preview extension).

**Comment by mikermesh** [comment]
Thanks for providing the link. This pointed me in the right direction...I Azure CLI installed on my Linux subsystem but not on the Windows side...so Visual Studio didn't have an AzureCLIPath to grab the token. I installed the Azure CLI for Windows and did an az login. I am able to successfully debug from Visual Studio now.
